---
name: Ansible Release  # feel free to pick your own name

on:
  push:
    tags:
      - 'Version_*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: building collection
      run:  |
        VERSION_RELEASE=$(echo ${GITHUB_REF##*/} | grep -oP '(?<=Version_)[^ ]*')
        sed -i "s/version:.*/version: ${VERSION_RELEASE}/g" galaxy.yml
        git commit -am "new version from tag ${VERSION_RELEASE}"
        git push
        ./build_collection.sh
      shell: bash

    - name: Relase new version
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: ./releases/*.tar.gz
...
